# Generated by Django 5.1.6 on 2025-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('popularity_score', models.FloatField()),
                ('weight', models.FloatField()),
                ('images', models.JSONField()),
            ],
        ),
    ]
